steps:
  - name: node:18.13.0
    entrypoint: npm
    args: ["install"]
  - name: env-variables
    entrypoint: npm
    args: ["run"]
    env:
      - "DATABASE_URL=${_DATABASE_URL}"
      - "DOMAIN_NAME=${_DOMAIN_NAME}"
      - "GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}"
      - "GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}"
      - "NEXT_PUBLIC_HOST_URL=${_NEXT_PUBLIC_HOST_URL}"
      - "NEXT_PUBLIC_TRPC_SEREVR_URL=${_NEXT_PUBLIC_TRPC_SEREVR_URL}"
      - "NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}"
      - "NEXTAUTH_URL=${_NEXTAUTH_URL}"
      - "NM_AUTH_EMAIL=${_NM_AUTH_EMAIL}"
      - "NM_CLIENT_ID=${_NM_CLIENT_ID}"
      - "NM_CLIENT_SECRET=${_NM_CLIENT_SECRET}"
      - "NM_DEFAULT_FROM_EMAIL=${_NM_DEFAULT_FROM_EMAIL}"
      - "NM_DKIM_PRIVATE_KEY=${_NM_DKIM_PRIVATE_KEY}"
      - "NM_REDIRECT_URI=${_NM_REDIRECT_URI}"
      - "NM_REFRESH_TOKEN=${_NM_REFRESH_TOKEN}"
  - name: node:18.13.0
    entrypoint: npm
    args: ["run", "build:server"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
options:
  logging: "NONE"
serviceAccount: "taskflow-space@appspot.gserviceaccount.com"
timeout: "1600s"
